name: edumate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  card_swiper: ^3.0.1
  chewie: ^1.12.1
  cloud_firestore: ^6.0.0
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  fab_circular_menu: ^1.0.2
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  firebase_storage: ^13.0.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^7.1.2
  flutter_hooks: ^0.21.2
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.9.0
  google_fonts: ^6.3.0
  google_sign_in: ^7.1.1
  hooks_riverpod: ^2.6.1
  image: ^4.5.4
  image_picker: ^1.1.2
  lottie: ^3.3.1
  overlay_support: ^2.1.0
  percent_indicator: ^4.2.5
  share_plus: ^11.0.0
  twitter_login: ^4.4.2
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  video_player: ^2.10.0
  video_thumbnail: ^0.5.6
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/