// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJFCQvfCWFcT8xMkdhILdQh2JxCAL-T0g',
    appId: '1:742583875515:web:9af2c34ef3adb384cbb69e',
    messagingSenderId: '742583875515',
    projectId: 'edumate-app-64b00',
    authDomain: 'edumate-app-64b00.firebaseapp.com',
    storageBucket: 'edumate-app-64b00.appspot.com',
    measurementId: 'G-YXLVBEKS17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNnfQIFX-zn4Xzsrozodj4YQG6ndiA9R8',
    appId: '1:742583875515:android:93867773fe6fb3a4cbb69e',
    messagingSenderId: '742583875515',
    projectId: 'edumate-app-64b00',
    storageBucket: 'edumate-app-64b00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMDyOSsG7HZ2fGfOoRPUUpGjtaPIxyfZ4',
    appId: '1:742583875515:ios:bccf888fb7dc2a1fcbb69e',
    messagingSenderId: '742583875515',
    projectId: 'edumate-app-64b00',
    storageBucket: 'edumate-app-64b00.appspot.com',
    iosClientId: '742583875515-so4pisbrd1b3ojnp894bhe4701bfsi65.apps.googleusercontent.com',
    iosBundleId: 'hack.techies.edumate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMDyOSsG7HZ2fGfOoRPUUpGjtaPIxyfZ4',
    appId: '1:742583875515:ios:bccf888fb7dc2a1fcbb69e',
    messagingSenderId: '742583875515',
    projectId: 'edumate-app-64b00',
    storageBucket: 'edumate-app-64b00.appspot.com',
    iosClientId: '742583875515-so4pisbrd1b3ojnp894bhe4701bfsi65.apps.googleusercontent.com',
    iosBundleId: 'hack.techies.edumate',
  );
}
